Hw06 email
Cryosphere/nodejs-homework-RestAPI pull request #5
Opened 2023-08-15 14:30 UTC by Cryosphere

Check it, please

2023-08-15 18:01 UTC, ceREAL133 requested changes

2023-08-15 18:01 UTC, ceREAL133 commented on controllers/auth/register.js
> +    const emailTransport = nodemailer.createTransport({
this functionality. (Mail transport etc.) should be in separate file

2023-08-15 18:01 UTC, ceREAL133 commented on controllers/auth/resendingEmail.js
> +      to: email,
you have already used this piece of code. Reuse

2023-08-15 19:58 UTC, Cryosphere commented
Check, please

2023-08-16 08:54 UTC, ceREAL133 approved these changes

2023-08-16 09:01 UTC, merged